title: "Navigations"
description: |
  Here are all the available navigation patterns for the 2020 grad show website.

patterns:
  logo-nav:
    title: "Logo Navigation"
    description: |
      The logo navigation can be used to jump back to the home page at anytime.
    padding: 1em
