title: "Navigations"
description: |
  Here are all the available navigation patterns for the 2020 grad show website.

patterns:
  logo-nav:
    title: "Logo Navigation"
    description: |
      The logo navigation can be used to jump back to the home page at anytime.
    padding: 1em
  main-nav:
    title: "Main Navigation"
    description: |
      The main navigation can be used to travel to the designers or supports page.
    padding: 1em
  filter-nav:
    title: "Filter Navigation"
    description: |
      This navigation is used to filter designers based on their preferred design practice.
  ham-nav:
    title: "Hamburger Navigation"
    description: |
      The hamerburger navigation is used to reduced the size of the main navigation links at smaller screens sizes.
  social-nav:
    title: "Social Navigation"
    description: |
      The social navigation contains links to the official Algonquin Design social media pages.
  additional-nav:
    title: "Additional Navigations"
    description: |
      The additional navigation links contain other useful links for the footer.
