title: "Sections"
description: |
  Here are all the available section patterns for the 2020 grad show website.

patterns:
  gradient-section:
    title: "Background Section"
    description: |
      The background section contains background info on our graduating brand 'Anthology' and link to the graduates page. Should be used on the homepage.
  graduates-section:
    title: "Gradutates Section"
    description: |
      The graduates section contains the list of all the 2020 Algonquin College graphic design graduates.
  grad-show-info:
    title: "Information Section"
    description: |
      The information section contains the neccessary info on the 2020 AC Grad Show.
  grad-details:
    title: "Graduate Details"
    description: |
      The graduate details pattern give all the details about the relevant graduate.
    fields:
      - name: data
        type: object
        data:
          source: "site.grads[0]"
          type: grads
  grad-pieces:
    title: "Graduate Pieces"
    description: |
      The graduate pieces pattern diplays the relevant graduates portfolio pieces.
    fields:
      - name: data
        type: object
        data:
          source: "site.grads[0]"
          type: grads
