title: "Cards"
description: |
  Here are all the available card patterns for the 2020 grad show website.

patterns:
  teacher-card:
    title: "Teacher Card"
    description: |
      Standard Card layout to showcase the respective prof and their subject taught.
    padding: 1em
    width: 20em
    fields:
      - name: data
        type: object
        data:
          source: "site.teachers[0]"
          type: teacher
  grad-card:
    title: "Graduates Card"
    description: |
      The graduates card is used to link to the its respective graduates information page. It contains a first name, last name and headshot image of the graduate
    padding: 1em
    width: 20em
    fields:
      - name: data
        type: object
        data:
          source: "site.grads[0]"
          type: grad
